### ISSUE TITLE
Extensions disappear with gradle daemon after first run

### ISSUE THREAD

**Issue by iwan-aucamp-cs** [asciidoctor/asciidoctor-gradle-plugin#222]
When using extensions like asciidoctor-diagram they are only available for the first build under gradle daemon - on subsequent executions they are missing.

I have set up a project to reproduce this here: https://gitlab.com/iwan.aucamp/public-scratchpad/tree/master/asciidoctor-gradle-diagrams_issue

Output:

```
iwana@iwana-nb.concurrent.systems:~
$ tar -jxf <(curl --silent https://gitlab.com/iwan.aucamp/public-scratchpad/repository/master/archive.tar.bz2) --strip-components=1 --wildcards -C /var/tmp/ '*/asciidoctor-gradle-diagrams_issue/'
iwana@iwana-nb.concurrent.systems:~
$ (
> cd /var/tmp/asciidoctor-gradle-diagrams_issue/
> ./gradlew --stop 
> ./gradlew clean asciidoctor
> ./gradlew clean asciidoctor
> )
Stopping Daemon(s)
1 Daemon stopped
Starting a Gradle Daemon, 10 stopped Daemons could not be reused, use --status for details

BUILD SUCCESSFUL in 9s
2 actionable tasks: 1 executed, 1 up-to-date

> Task :asciidoctor 
asciidoctor: WARNING: test-article.asciidoc: line 63: invalid style for listing block: graphviz
asciidoctor: WARNING: test-article.asciidoc: line 97: invalid style for listing block: plantuml


BUILD SUCCESSFUL in 0s
2 actionable tasks: 2 executed
```

The reason this is happening is because the extentions (i.e. `Asciidoctor::Extensions.instance_variable_get(:@groups)`) is being cleared after the task executes:

https://github.com/asciidoctor/asciidoctor-gradle-plugin/blob/64aac8a/src/main/groovy/org/asciidoctor/gradle/AsciidoctorTask.groovy#L886

```
            if (asciidoctor) {
                asciidoctor.unregisterAllExtensions()
            }
```

I'm not clear why this is being done though though - this was changed in https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/213 ( https://github.com/asciidoctor/asciidoctor-gradle-plugin/commit/0b9d614fb10fcf79747588e0a8257fca5b96033a )

Removing `asciidoctor.unregisterAllExtensions()` makes the problem go away but I'm not entirely clear why it was added in the first place. It seems like this would also cause problems with multiple asciidoctor tasks.

**Comment by sbrannen** [comment]
FYI: the JUnit Team is experiencing the same problem with the Gradle daemon running as discussed here: https://github.com/junit-team/junit5/issues/1222

**Comment by wilkinsona** [comment]
This problem also affects builds that are not using the daemon but are using `--continuous`. The extensions are available the first time the build runs but are not available after that.

**Comment by aalmiray** [comment]
Does downgrading solve the problem? If so then the recent optimizations will have to be removed

**Comment by wilkinsona** [comment]
> Does downgrading solve the problem?

Yes, it does. The problem doesn't occur with 1.5.3.

**Comment by aalmiray** [comment]
@wilkinsona OK. Will look at options to keep the optimization with different code. Otherwise it's rollback. Thank you for pointing this out 😄

**Comment by iwan-aucamp-cs** [comment]
I use this hack to make 1.5.7 work (and do some other things):

```
org.asciidoctor.gradle.AsciidoctorProxyImpl.metaClass.invokeMethod = { String name, arguments ->
    if ( ( name == "unregisterAllExtensions" )
        && ( Arrays.stream( Thread.currentThread().getStackTrace() )
            .filter( {stackTraceElement -> stackTraceElement.className == "org.asciidoctor.gradle.AsciidoctorTask" && stackTraceElement.methodName == "withAsciidoctor" } )
            .count() > 0 ) )
    {
        System.err.println "org.asciidoctor.gradle.AsciidoctorProxyImpl.metaClass.invokeMethod: Ignoring call to unregisterAllExtensions from org.asciidoctor.gradle.AsciidoctorTask.withAsciidoctor"
        return
    }
    else if ( ( name == "renderFile" ) )
    {
        arguments[1].attributes.invoke_to_dir = arguments[1].to_dir
        arguments[1].attributes.invoke_base_dir = arguments[1].base_dir
        System.err.println "org.asciidoctor.gradle.AsciidoctorProxyImpl.metaClass.invokeMethod: ${name} ${arguments}"
        return org.asciidoctor.gradle.AsciidoctorProxyImpl.metaClass.getMetaMethod(name, arguments).doMethodInvoke(delegate, arguments);
    }
    return org.asciidoctor.gradle.AsciidoctorProxyImpl.metaClass.getMetaMethod(name, arguments).doMethodInvoke(delegate, arguments);
}
```

**Comment by ldaley** [comment]
I know very little about Asciidoctor extensions, so will need help on that front.  

This looks suspicious: https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/213/files#diff-467e6edfd5f5943cc0fdf8e11457f034R870

Looks like the extensions are registered when the runtime is created, but then unregistered after each use. This matches the reported behaviour. 

The fix should be something like registering the extensions with the runtime before each use, not at construction time.

Given that I have no reproducer, and that the fix should be easier for someone with more knowledge of Asciidoctor extensions, I don't plan to submit a fix.

**Comment by eriwen** [comment]
Thanks for the note @ldaley. I've taken us back to v1.5.3 of this plugin for Gradle. Asciidoctor is now so much faster without docbook that overall the speed improvement far outweighs loss of cacheability. 

Will you be able to help out here @breskeby?

**Comment by mojavelinux** [comment]
This regression is causing users a lot of trouble and hurting the great reputation of this plugin. @aalmiray would it be possible to move forward with a release that rolls it back?

**Comment by ldaley** [comment]
I think that would be a mistake. 

Making it slower for everyone because nobody can be bothered to provide a failing test case doesn’t make much sense to me.

It looks quite easy to fix.

**Comment by wilkinsona** [comment]
A sample that reproduces the problem was provided six months ago when the issue was first raised.

**Comment by ldaley** [comment]
I did indeed miss that. 

I just looked at the code again and it actually looks correct. We unregister any extensions set in the withAsciidoctor {} call. Something deeper is going on in the layers under this plugin. Having a quick look around in the lib reveals `ExtensionGroup` which sounds ideal for this case, but the Groovy shim is set up not to work with this.

@breskeby can you please turn the provided reproducer into a test case within the project, then let's discuss how to fix. 

I'm not willing to go back to waiting 5s to build my docs every change.

**Comment by iwan-aucamp-cs** [comment]
@ldaley please see the workaround - that might make the reason why this is failing easier to understand.

The workaround has been working without issues for me for some time.

**Comment by ldaley** [comment]
@iwan-aucamp-cs that will work as long as you don't try and use a different set of extensions in the same runtime. So, unfortunately it doesn't help.

**Comment by ysb33r** [comment]
Where is the 5s wait coming from?


Sent from my Samsung device

-------- Original message --------

**Comment by breskeby** [comment]
I've added a testcase demoing the issue at https://github.com/asciidoctor/asciidoctor-gradle-plugin/pull/238 it seems the issue is with required modules. havn't looked into fixing yet

**Comment by nikolay-martynov** [comment]
"org.gradle.daemon=false" in gradle.properties helps somewhat. If you build from IDEA then you have to "./gradlew --stop" after changing build.gradle. When other non-asciidoc changes are made, incremental build just skips asciidoctor task and build goes on.

**Comment by ldaley** [comment]
@ysb33r 

> Where is the 5s wait coming from?

Bootstrapping JRuby.

**Comment by ysb33r** [comment]
> Removing asciidoctor.unregisterAllExtensions() makes the problem go away but I'm not entirely clear why it was added in the first place. It seems like this would also cause problems with multiple asciidoctor tasks.

I think that was done to reduce the start-up time. Thre is an additional probloem too though. The current transitive version of GroovyDSL uses singleton state and it deregisters extensions after use as well. So a first fix could be just to bump it to the later version which now has a fix for this and modify the 1.5.x series of the pugin to use this modification.

Reloading is required as extensions may change between subsequent executions of the task.

**Comment by ysb33r** [comment]
This might be the problem -> https://github.com/asciidoctor/asciidoctorj-groovy-dsl/blob/v1.0.0.Alpha2/src/main/groovy/org/asciidoctor/groovydsl/AsciidoctorExtensions.groovy

**Comment by ysb33r** [comment]
I have added some comment to asciidoctor/asciidoctor-gradle-plugin#238 that explain the fix that I think can be added. It seems to work on the development-1.6 branch, but that code is to different to simply cherry-pick a change..

**Comment by ysb33r** [comment]
As reported by @eriwen via Twitter the problem still persists in 1.5.8. What we know so far is that
- @breskeby functional test does not reproduce the extensions problem
- The @ysb33r fix to not use the singleton version of GroovyDSL has not contibuted.
- Asciidoctorj-diagram also disappears (#220), so it is not just a GroovyDSL problem.

**Comment by ysb33r** [comment]
ANother important context is this from @moschkom in #166.

> At Hackergarten Basel we tried to investigate this issue.
We were able to see that AsciidoctorExtensions (package 'org.asciidoctor.groovydsl' in repository asciidoctorj-groovy-dsl) is called for each Asciidoctor-Task. First the extensions() method is called to add the closure. This seems to work fine for all three tasks. Afterwards registerTo() is invoked to run the closure. Unfortunately the static field REGISTERED_EXTENSIONS is empty for the two last tasks (asciidoctorA and asciidoctorB). We were not able to find out why. But maybe this is a hint for the next looking into this issue.

**Comment by ysb33r** [comment]
@eriwen Is ti possible to furnish me with a example project that I can try. I just wrote a simple one and ran it in two modes:
- 100 times with `--rerun-tasks` as parameter
- Second time in continuous mode, with another job changing the input adoc files extenrally.

In both cases I got consistent extension reloads.

**Comment by ysb33r** [comment]
This is the `build.gradle` I used for testing.

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath files('../../build/libs/asciidoctor-gradle-plugin-1.5.9-SNAPSHOT.jar')
    }
}

apply plugin : 'org.asciidoctor.convert'

asciidoctor {
    sourceDir 'docs'

    extensions {
        println "**** Extension loaded ${new Date()}****"
    }
}
```

**Comment by ysb33r** [comment]
Verions 1.5.8.1 as been released as the wrong versions of AsciidoctorJ and GroovyDSL were used in the 1.5.8. release. I am not sure where this will actually solve the problem, but we need to at least baseline with the correct versions before continuing.

**Comment by ldaley** [comment]
One thing that would be worth doing is sorting out the complexity in the state management to avoid statics. In doing this, it would probably help to use the asciidoctorj extension group concept when registering/unregistering extensions.

**Comment by ysb33r** [comment]
> One thing that would be worth doing is sorting out the complexity in the state management to avoid statics. In doing this, it would probably help to use the asciidoctorj extension group concept when registering/unregistering extensions.

That is how it works in the 2.0 development.  Extensions can be added globally and customised on  aper-task basis if required.

**Comment by ldaley** [comment]
I moreso meant the Groovy DSL layer, that uses static state as part of its implementation.

**Comment by ysb33r** [comment]
> I moreso meant the Groovy DSL layer, that uses static state as part of its implementation.

That has already been taken care of the 1.0.0-Alpha.3 release of the extensions DSL has marked the static state as deprecated and it is now possible to creates instances ofthe extension registry. The  1.5.8.1 release already utilises this functionality and cannot use any older version of the extensions DSL.

**Comment by bmuschko** [comment]
@ysb33r What's the status of this issue? Am I reading your comment correctly that the issue will be fixed with version 2.0 of the plugin? If yes, do you have a rough ETA on a release date?

I also ran into the problem using `buildSrc`. At the very least, the [documentation](https://github.com/asciidoctor/asciidoctor-gradle-plugin#as-build-dependency) should be updated to reflect the shortcoming (and potentially propose a workaround e.g. running with `--no-daemon` in the meantime).

**Comment by ysb33r** [comment]
@bmuschko Try 2.0-alpha.3

**Comment by bmuschko** [comment]
@ysb33r Looks like this version is not yet available on JCenter. Is there any other repository and I get it from? If it hasn't been published yet then I will build it myself.

**Comment by ysb33r** [comment]
Alpha.3 is in the Gradle Plugin Portal


Sent from my Samsung device

-------- Original message --------

**Comment by ysb33r** [comment]
@dcp65 there was an issue plublisging `org.asciidoctor.convert` (See https://discuss.gradle.org/t/cant-publish-plugin-org-asciidoctor-convert/27651/6). This has now been corrected, but we shall only know once alpha.4 is pushed for publication.

The workaround you need atm is to do 

```groovy
plugins {
    id 'org.asciidoctor.jvm.base' version '2.0.0-alpha.3' apply false
}

apply plugin : 'org.asciidoctor.convert'
```

This works because both plugins are in the same Jar.

**Comment by ysb33r** [comment]
Can you post more of your build.gradle file?

**Comment by dcp65** [comment]
Sorry. My fault. I was applying the asciidoctor.convert plugin in the wrong place in my build file. 

However, now I'm getting a different error:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.asciidoctor.extension.JavaExtensionRegistry.docinfoProcessor(Lorg/asciidoctor/extension/DocinfoProcessor;)V
        at io.spring.asciidoctor.SpringAsciidoctorExtensionRegistry.register(SpringAsciidoctorExtensionRegistry.java:31)
        at org.asciidoctor.extension.internal.ExtensionRegistryExecutor.registerAllExtensions(ExtensionRegistryExecutor.java:21)
        at org.asciidoctor.internal.JRubyAsciidoctor.registerExtensions(JRubyAsciidoctor.java:118)
        at org.asciidoctor.internal.JRubyAsciidoctor.processRegistrations(JRubyAsciidoctor.java:107)
        at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:87)
        at org.asciidoctor.internal.JRubyAsciidoctor.create(JRubyAsciidoctor.java:83)
        at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:823)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.getAsciidoctorInstance(AsciidoctorJavaExec.groovy:80)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:42)
        at org.asciidoctor.gradle.remote.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:128)
```

Here's my build.gradle:

```
buildscript {
    dependencies {
        classpath "io.github.swagger2markup:swagger2markup-gradle-plugin:1.3.3"
        classpath "io.github.swagger2markup:swagger2markup-import-files-ext:1.3.3"
    }
}

repositories {
    maven {
        url 'https://repo.spring.io/release'
    }
    jcenter()
}

plugins {
    id 'org.asciidoctor.jvm.base' version '2.0.0-alpha.3' apply false
}

apply plugin: 'org.asciidoctor.convert'

dependencies {
    asciidoctor 'io.spring.asciidoctor:spring-asciidoctor-extensions:0.1.3.RELEASE'
    asciidoctor 'org.asciidoctor:asciidoctorj-pdf:1.5.0-alpha.16'
}

ext {
    asciiDocOutputDir = file("${buildDir}/asciidoc/generated")
    docBuildDir = file("${project.buildDir}/doc")
}

apply plugin: 'io.github.swagger2markup'

convertSwagger2markup {
    swaggerInput System.getProperty("swaggerDef", "src/swagger/swagger.json")
    outputDir asciiDocOutputDir
    config = [
            'swagger2markup.pathsGroupedBy': 'TAGS',
            'swagger2markup.extensions.dynamicPaths.contentPath' : file('src/asciidoc/extensions/paths').absolutePath
    ]
}

asciidoctor {
    dependsOn(convertSwagger2markup)
    separateOutputDirs = false
    sourceDir = file("src/asciidoc/")
    sources {
        include myguide.adoc'
    }
    resources {
        from(sourceDir) {
            include 'images/**'
        }
        from(sourceDir) {
            include 'assets/js/**'
        }
    }

    outputDir docBuildDir
    backends = ['html5', 'pdf']
    attributes = [
            'doctype'           : 'book',
            'toc'               : 'left',
            'toclevels'         : '3',
            'source-highlighter': 'prettify',
            'revnumber'         : '2.1',
            'docinfo'           : 'shared',
            'pdf-stylesdir'     : 'theme',
            'pdf-style'         : 'mystyle',
            'generated'         : asciiDocOutputDir
    ]
}

```

**Comment by ysb33r** [comment]
@dcp65 I have not had a chance to check yet, but I suspect the issue is that the spring extensions are not compatible with the API changes in asciidoctorj-1.6.0-alpha.6

**Comment by wilkinsona** [comment]
That certainly appears to be the case. @dcp65, please open an issue [here](https://github.com/spring-io/spring-asciidoctor-extensions/issues) and we'll see what can be done about that.

Given that there are breaking changes in 1.6, can we please have a fix for this issue in a 1.5 release?

**Comment by ysb33r** [comment]
@wilkinsona That will require some backport of the 2.x functionality into 1.5. It is do-able. I'll see what can be done.

**Comment by wilkinsona** [comment]
Great stuff! Thank you.

**Comment by mojavelinux** [comment]
Thank you @ysb33r! Hero!

**Comment by aalmiray** [comment]
Release `1.5.9` is out. Please give it a try and let us know if it solved the problem on your side.

**Comment by dcp65** [comment]
Upgraded the plugin to 1.5.9. Now I get this:

```
Oct 17, 2018 3:56:05 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
SEVERE: (NoMethodError) asciidoctor: FAILED: /Users/dcporter/projects/ife-onboard-server/ife-onboard-docs/src/asciidoc/ife-onboard-apiguide.adoc: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
Exception in thread "main" org.asciidoctor.gradle.backported.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process /Users/dcporter/projects/ife-onboard-server/ife-onboard-docs/src/asciidoc/ife-onboard-apiguide.adoc using backend html5
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_convertFiles_closure3.doCall(AsciidoctorJavaExec.groovy:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:434)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2163)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.convertFiles(AsciidoctorJavaExec.groovy:56)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.access$0(AsciidoctorJavaExec.groovy)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_run_closure2.doCall(AsciidoctorJavaExec.groovy:50)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec$_run_closure2.call(AsciidoctorJavaExec.groovy)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2125)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2110)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2151)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.run(AsciidoctorJavaExec.groovy:48)
        at org.asciidoctor.gradle.backported.AsciidoctorJavaExec.main(AsciidoctorJavaExec.groovy:191)
```

**Comment by bmuschko** [comment]
I just gave 1.5.9 a shot. It seems that my AsciidoctorJ extension (implementation of `DocinfoProcessor`) isn't executed at all. If you want to try, upgrade [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/buildSrc/build.gradle.kts#L13) and add a `println` statement [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/buildSrc/src/main/kotlin/com/bmuschko/asciidoctor/TabbedCodeBlockDocinfoProcessor.kt#L10).

**Comment by ysb33r** [comment]
@dcp65 Is it posible to provide a smaller project that reproduces your problem? I suspect it is related to JRuby version mismatch or library pollution.

**Comment by ysb33r** [comment]
> I just gave 1.5.9 a shot. It seems that my AsciidoctorJ extension (implementation of DocinfoProcessor) isn't executed at all. If you want to try, upgrade here and add a println statement here.

@bmuschko Running your project, I see the classpath used to run AciidoctorJ is
```
/..../org.asciidoctor/asciidoctor-gradle-plugin/1.5.9/69873a916988a11763c9f7fb57cabad07fb2b8b3/asciidoctor-gradle-plugin-1.5.9.jar, /Users/schalkc/.gradle/wrapper/dists/gradle-4.10.2-bin/cghg6c4gf4vkiutgsab8yrnwv/gradle-4.10.2/lib/groovy-all-2.4.15.jar, /..../org.asciidoctor/asciidoctorj-groovy-dsl/1.0.0.Alpha3/947c76e55185689df20ed446ee6dff1a8f698e0b/asciidoctorj-groovy-dsl-1.0.0.Alpha3.jar, /..../org.asciidoctor/asciidoctorj/1.5.7/8e8c1d8fc6144405700dd8df3b177f2801ac5987/asciidoctorj-1.5.7.jar, /..../org.jruby/jruby-complete/9.1.16.0/dfadacbdecc9c93a13871cc8242b92394d71631f/jruby-complete-9.1.16.0.jar, /..../com.beust/jcommander/1.35/47592e181b0bdbbeb63029e08c5e74f6803c4edd/jcommander-1.35.jar, /..../org.codehaus.groovy/groovy/2.4.15/74b7e0b99526c569e3a59cb84dbcc6204d601ee6/groovy-2.4.15.jar, /Users/schalkc/.gradle/wrapper/dists/gradle-4.10.2-bin/cghg6c4gf4vkiutgsab8yrnwv/gradle-4.10.2/lib/gradle-core-4.10.2.jar
```

I suspect the JAR of your extension is not being passed onto Asciidoctor - will investigate

**Comment by dcp65** [comment]
@ysb33r I've tried running a number of the [asciidoctor-gradle-examples](https://github.com/asciidoctor/asciidoctor-gradle-examples) with 1.5.9. They all fail, but with a different error :(

```
Execution failed for task ':asciidoc-to-github-pages-example:asciidoctor'.
...
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/scripts/ScriptOrigin
```

**Comment by ysb33r** [comment]
@dcp65 Looks like like I really messed up this backport, but thanks for the pointer. I'll rather use the exmaples to reproduce the problem. It seems that both your issue and that of @bmuschko is related to the classpath that is passed to asciidoctor.

**Comment by ysb33r** [comment]
@bmuschko I tracked down your issue.

* Because you were building the Asciidoctor extension in `buildSrc` and did not add it explicitly to the `asciidoctor` configuration, it just relied on the fact that Asciidoctor 1.5.8.1 (and earlier) ran in the same process as Gradle. I have a fix for that which will go into 1.5.9.1.

* However, even given the above you were building the extension against AsciidoctorJ 1.6.0-alpha.7. This leads to two versions of AsciidoctorJ on the classpath. I managed to get it to work by adding the following to `build.gradle.kts` (You should really do this in your custom UserGuide plugin).

```kotlin
import org.asciidoctor.gradle.AsciidoctorExtension

configure<AsciidoctorExtension> {
        version = "1.6.0-alpha.7"
}
```

**Comment by ysb33r** [comment]
@dcp65 The `ScriptOrigin` issue has been resolved. It is required for Gradle 4.0, but fails on earlier versions of Gradle. That was the problem with the Asciidoctor Gradle examples. This will be in the 1.5.9.1 release.

**Comment by ysb33r** [comment]
> Oct 17, 2018 3:56:05 PM org.asciidoctor.internal.JRubyAsciidoctor renderFile
SEVERE: (NoMethodError) asciidoctor: FAILED: /Users/dcp/projects/my-project/my-project-docs/src/asciidoc/my-apiguide.adoc: Failed to load AsciiDoc document - undefined method `start_with?' for nil:NilClass
Exception in thread "main" org.asciidoctor.gradle.backported.AsciidoctorRemoteExecutionException: Error running Asciidoctor whilst attempting to process /Users/dcp/projects/my-project/my-project-docs/src/asciidoc/my-apiguide.adoc using backend html5

@dcp65 Can you tell me which JDK, AsciidoctorJ, Gradle & JRuby versions are involved?

**Comment by jlstrater** [comment]
@ysb33r If it helps, I applied the current development branch to my spring rest docs example. Here's the build scan https://scans.gradle.com/s/gqkiu7n4t3l62/failure?openFailures=WzBd&openStackTraces=WzEse31d#top=0 There's still an issue with extensions. :/

**Comment by ysb33r** [comment]
@jlstrater Do you have the latest copy of the dev branch? You might have caught the commit, before I fixed the `ExtensionRegistry` issue.

**Comment by ysb33r** [comment]
> Yes. I even tried it again and it's still the same. The most recent commit I have is commit 0c17a9bffaa3adc4d922ae3ce0ae09539717c16e

Yes that commit fixed it for me. Oh well, back to the drawing board.

**Comment by jlstrater** [comment]
Should I try another config? a different version of java or gradle or something like that?

**Comment by ysb33r** [comment]
> Should I try another config? a different version of java or gradle or something like that?

It would be useful to know which versions of Gradle / Asciidoctor / JRuby / Java you used.

**Comment by ysb33r** [comment]
@jlstrater Try with 1adc02942fbc64329a38a5b411b937fb70a6d203

**Comment by dcp65** [comment]
Just tried asciidoctor-gradle-plugin 1.5.9.1 (with a dependency on asciidoctorj 1.5.8) on my project and the docs build as expected. 

The spring-asciidoctor-extensions that my project relies on are used in repeated builds.

Thanks @ysb33r.

**Comment by mojavelinux** [comment]
Hallelujah! Great work, @ysb33r!
