### ISSUE TITLE
Cannot resolve external dependency from subproject

### ISSUE THREAD

**Issue by ari** [asciidoctor/asciidoctor-gradle-plugin#559]
When trying to apply the plugin to a subproject I get this error:

```
$ ./gradlew design:asciidoctor
> Task :design:asciidoctor FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':design:asciidoctor'.
> Could not resolve all files for configuration ':design:detachedConfiguration2'.
   > Cannot resolve external dependency org.asciidoctor:asciidoctorj:2.2.0 because no repositories are defined.
     Required by:
         project :design
   > Cannot resolve external dependency org.jruby:jruby-complete:9.1.0.0 because no repositories are defined.
     Required by:
         project :design
```

Config is pretty simple, in the top level gradle:

```
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    id 'org.asciidoctor.jvm.convert' version '3.2.0'
}

repositories {
    jcenter()
}
```

**Comment by ari** [comment]
After more investigation, this happens when trying to use the plugin from a subproject. If I add this to the subproject it works:

    repositories {
        jcenter()
    }

So this plugin isn't picking up the repository from the parent project as it should.

**Comment by ascheman** [comment]
As of today adding

```groovy
repositories {
    mavenCentral()
}
```

to `build.gradle` resolves the problem.

However, I would expect that dependency handling should be resolved by plugin download?

**Comment by abelsromero** [comment]
> However, I would expect that dependency handling should be resolved by plugin download?

That's not the case. The Plugin could add dependency(ies) identified by a GAV, but where these are located and how to download them is part of the standard `repositories {}` configuration.
The exception is the gems management where some facilities are offered because the process is slightly differenet, but still not the whole end-to-end process.

**Comment by ascheman** [comment]
> > However, I would expect that dependency handling should be resolved by plugin download?
> 
> That's not the case. The Plugin could add dependency(ies) identified by a GAV, but where these are located and how to download them is part of the standard Gradle `repositories {}` configuration. The exception is the gems management where some facilities are offered because the process is slightly differenet, but still not the whole end-to-end process.

Thanks for the clarification, @abelsromero. I am not so deep into Gradle. From Maven I am used to a complete dependency resolution by the plugin resolver itself.
